# Generated by Django 4.0.6 on 2022-07-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Url')),
                ('previewContent', models.CharField(max_length=120, verbose_name='Предпросматриваемый контент')),
                ('content', models.TextField(blank=True)),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('previewPhoto', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Предпросматриваемое фото')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('modelPhoto', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Чертеж')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категории проектов',
                'verbose_name_plural': 'Категории проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=64, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.characteristic', verbose_name='Характеристика')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Характеристика проекта',
                'verbose_name_plural': 'Характеристики проектов',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory', verbose_name='Категория проекта'),
        ),
    ]
