# Generated by Django 4.0.6 on 2022-07-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristic',
            old_name='characteristic',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='projectcharacteristic',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characteristic_name', to='projects.characteristic', verbose_name='Характеристика'),
        ),
    ]
