# Generated by Django 4.0.6 on 2022-07-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_characteristic_characteristic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcharacteristic',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='params', to='projects.characteristic', verbose_name='Характеристика'),
        ),
    ]
