# Generated by Django 4.0.6 on 2022-07-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'Категория(ю) меню', 'verbose_name_plural': 'Категории меню'},
        ),
        migrations.AlterModelOptions(
            name='menusubcategory',
            options={'verbose_name': 'Подкатегория(ю) меню', 'verbose_name_plural': 'Подкатегории меню'},
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menusubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='shop.menucategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='menusubcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='menusubcategory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
