# Generated by Django 4.0.6 on 2022-07-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_characteristic_product_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=20, verbose_name='Скидка'),
        ),
    ]
