# Generated by Django 4.0.6 on 2022-07-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Код товара'),
        ),
    ]
