# Generated by Django 4.0.6 on 2022-07-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characteristics', to='shop.productcharacteristic', verbose_name='Характеристики продукта'),
        ),
    ]
