# Generated by Django 4.0.6 on 2022-07-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.ManyToManyField(null=True, related_name='characteristics', to='shop.productcharacteristic', verbose_name='Характеристики продукта'),
        ),
    ]
