# Generated by Django 4.0.6 on 2022-07-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_characteristics_product_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='params',
        ),
    ]
