# Generated by Django 4.0.6 on 2022-07-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.ManyToManyField(related_name='params', to='shop.productcategory', verbose_name='Категория продукта'),
        ),
    ]
