# Generated by Django 4.0.6 on 2022-07-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_productcharacteristic_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.ManyToManyField(null=True, related_name='params', to='shop.productcharacteristic', verbose_name='Категория продукта'),
        ),
    ]
