# Generated by Django 4.0.6 on 2022-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.ManyToManyField(null=True, related_name='params', to='shop.productcharacteristic', verbose_name='Характеристики продукта'),
        ),
    ]
