# Generated by Django 4.0.6 on 2022-07-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_content_alter_product_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photoCard',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография в карточке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография в каталоге'),
        ),
    ]
