# Generated by Django 4.0.6 on 2022-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_photocard_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contentPreview',
            field=models.CharField(max_length=128, verbose_name='Предпросматриваемый контент'),
        ),
    ]
