# Generated by Django 4.0.6 on 2022-07-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_productslider_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='Тип')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterField(
            model_name='productslider',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='params', to='shop.productcharacteristictype', verbose_name='Характеристика'),
        ),
    ]
