# Generated by Django 4.0.6 on 2022-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_productcharacteristic_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brend',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='product',
            name='diametr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Диаметр дымохода'),
        ),
        migrations.AddField(
            model_name='product',
            name='exitFire',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Выход дымохода'),
        ),
        migrations.AddField(
            model_name='product',
            name='glass',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Стекло'),
        ),
        migrations.AddField(
            model_name='product',
            name='inflow',
            field=models.BooleanField(blank=True, null=True, verbose_name='Приток воздуха из вне'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Материал топки'),
        ),
        migrations.AddField(
            model_name='product',
            name='open',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Открытие дверцы'),
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Мощность (Квт)'),
        ),
        migrations.AddField(
            model_name='product',
            name='water',
            field=models.BooleanField(blank=True, null=True, verbose_name='Водяной контур'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ширина'),
        ),
    ]
