# Generated by Django 4.0.6 on 2022-07-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_brend_product_depth_product_diametr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brend',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diametr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='exitFire',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glass',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inflow',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='open',
        ),
        migrations.RemoveField(
            model_name='product',
            name='place',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
    ]
