# Generated by Django 4.0.6 on 2022-07-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_product_brend_remove_product_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='shop.typecharacteristic', verbose_name='Тип'),
        ),
    ]
