# Generated by Django 4.0.6 on 2022-07-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_productcharacteristic_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('address', models.CharField(max_length=64, verbose_name='Адрес')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('mounting', models.BooleanField(verbose_name='Нужен ли монтаж')),
                ('paymentMethod', models.CharField(max_length=64, verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
