# Generated by Django 4.0.6 on 2022-08-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_requestmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='shop.productcategory', verbose_name='Категория')),
                ('filters', models.ManyToManyField(null=True, related_name='filters', to='shop.productcharacteristic', verbose_name='Фильтры')),
            ],
            options={
                'verbose_name': 'Подкатегория продукта',
                'verbose_name_plural': 'Подкатегории продуктов',
            },
        ),
    ]
