# Generated by Django 4.0.6 on 2022-08-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='slug',
        ),
    ]
