# Generated by Django 4.0.6 on 2022-08-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_productsubcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='shop.productsubcategory', verbose_name='Подкатегория продукта'),
        ),
    ]
